name: consession
description: A simple session package for Flutter that works on both mobile, web and (hopefully) desktop apps. 
version: 0.0.2
homepage: https://github.com/jhourlad/consession

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
